### ISSUE TITLE
Please add Production well data service to well data pane

### ISSUE THREAD

**Issue by Geospring** [wpears/groundwater#10]
Please add Production well data service to well data pane. 

If possible organize the data under two main headings

Domestic Well data
  Average Depth
  Min Depth
  Max Depth
  Well Count
  Well Count Polygons

Production Well Data 
  Average Depth
  Min Depth
  Max Depth
  Well Count
  Well Count Polygons

Thanks!

**Comment by wpears** [comment]
Could you possibly combine the services into a single service? Unless you feel that the production/domestic datasets have compelling reasons to be separated into different services.

**Comment by wpears** [comment]
The well data pane is in place. I'll need to you generate the zip files for the datasets (names identical to the layer names) and put them in the "Download" folder in the "GGI" folder on the staging NAS.

**Comment by Geospring** [comment]
Thanks Wyatt! I really appreciate it. We're still deciding if this dataset will be downloadable. I'll keep you posted.
