### ISSUE TITLE
Geocoder?

### ISSUE THREAD

**Issue by Geospring** [wpears/groundwater#13]
Hi Wyatt,

Juan and Chris had a well depth question about a specific address in the foothills.  I showed them the new well depth data on the map and they were very impressed..we were able to answer a question in 1 minute that would have taken 1 hour or more to do the old way!

They mentioned it would be nice to have a simple geocoder on the map so people can type in their address and see all of this great data in the context of where they live.

Thoughts?

**Comment by wpears** [comment]
Geocoder tentatively in place. I'm open to suggestions about its functionality.

**Comment by Geospring** [comment]
Wyatt, you're the man!  Thank you. The geocoder looks and works great.
