### ISSUE TITLE
GICIMA Dev Site

### ISSUE THREAD

**Issue by DWRbbrew** [wpears/groundwater#3]
I propose that we use the http://mrsbmapp21161/app/groundwater/ interactive map as the GICIMA development map application.  As such, I request that the services posted to "arcgis on mrsbmapp21157" are used by the GICIMA dev site http://mrsbmapp21161/app/groundwater/

This will allow testing of new and updated services prior to posting to the public, although it will also require additional maintenance of the dev map.

**Comment by wpears** [comment]
Fixed in [this commit](https://github.com/wpears/groundwater/commit/c9d4b9859269feb71c1bcc5a93a7e12426a37241).
