### ISSUE TITLE
Lyte Greyscale basemap

### ISSUE THREAD

**Issue by DWRbbrew** [wpears/groundwater#4]
Please add lt grayscale canvas to basemap options.

**Comment by wpears** [comment]
Turns out the widget I was using was a bit simpler than I thought, so I wrote something to replace it. [Fixed](https://github.com/wpears/groundwater/commit/ff70d278f67125461cbb2d84757494288b2d871a).

**Comment by DWRbbrew** [comment]
Sweet!   Thanks.  It looks good.
